services:
  gsp-heating-server:
    container_name: gsp-heating-server
    build: .
    network_mode: host
    environment:
      - PORT=${PORT:-3007}
      - MODBUS_HEATING_PORT=${MODBUS_HEATING_PORT:-8503}
      - DB_HOST=${DB_HOST:-postgres}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-gsp_db}
      - DB_USER=${DB_USER:-gsp_user}
      - DB_PASSWORD=${DB_PASSWORD:-gsp_password}
    # ports:
    #   - "3007:3007"
    #   - "8503:8503"
    restart: unless-stopped
    # networks:
    #   - gsp-net

networks:
  gsp-net:
    external: true
